import type { Track } from "./types"

export const sampleTracks: Track[] = [
  {
    id: "track-0",
    title: "Girls Just Want to Have Fun",
    artist: "Bladee",
    album: "Crest",
    duration: 134,
    cover: "/album-covers/miscellaneous_11.jpg",
    file: "/music/Girls Just Want to Have Fun.mp3",
  },
  {
    id: "track-1",
    title: "FLY ME TO THE MOON",
    artist: "Yoko Takahashi",
    album: "Neon Genesis Evangelion",
    duration: 272,
    cover: "/album-covers/miscellaneous_17.jpg",
    file: "/music/FLY ME TO THE MOON.mp3",
  },
  {
    id: "track-2",
    title: "Lady Brown",
    artist: "Nujabes",
    album: "365",
    duration: 217,
    cover: "/album-covers/miscellaneous_11.jpg",
    file: "/music/LadyBrown.mp3",
  },
  {
    id: "track-3",
    title: "French Toast",
    artist: "Westside Gunn",
    album: "Pray for Paris",
    duration: 180,
    cover: "/album-covers/miscellaneous_19.jpg",
    file: "/music/French Toast.mp3",
  },
  {
    id: "track-4",
    title: "Asleep Among Endives",
    artist: "Ichiko Aoba",
    album: "Asleep Among Endives",
    duration: 300,
    cover: "/album-covers/miscellaneous_20.jpg",
    file: "/music/Asleep Among Endives.mp3",
  },
  {
    id: "track-5",
    title: "Kagefumi",
    artist: "UK",
    album: "UK",
    duration: 300,
    cover: "/album-covers/miscellaneous_7.jpg",
    file: "/music/Kagefumi.mp3",
  },
  {
    id: "track-6",
    title: "PlaqueBoyMax",
    artist: "Fivio Foreign",
    album: "PlaqueBoyMax",
    duration: 240,
    cover: "/album-covers/miscellaneous_5.jpg",
    file: "/music/PlaqueBoyMax.mp3",
  },
  {
    id: "track-7",
    title: "360",
    artist: "Charli XCX",
    album: "Brat",
    duration: 180,
    cover: "/album-covers/miscellaneous_33.jpg",
    file: "/music/360 featuring robyn & yung lean.mp3",
  },
  {
    id: "track-8",
    title: "OMG",
    artist: "NewJeans",
    album: "NWJNS",
    duration: 300,
    cover: "/album-covers/miscellaneous_24.jpg",
    file: "/music/OMG.mp3",
  },
  {
    id: "track-9",
    title: "Best Friend",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 270,
    cover: "/album-covers/miscellaneous_25.jpg",
    file: "/music/The Closer I Get to You.mp3",
  },
  {
    id: "track-10",
    title: "Binibini",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 230,
    cover: "/album-covers/miscellaneous_26.jpg",
    file: "/music/Binibini.mp3",
  },
  {
    id: "track-11",
    title: "Black & Tan",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 180,
    cover: "/album-covers/miscellaneous_27.jpg",
    file: "/music/Black & Tan.mp3",
  },
  {
    id: "track-12",
    title: "Bubble Gum",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 210,
    cover: "/album-covers/miscellaneous_28.jpg",
    file: "/music/Bubble Gum.mp3",
  },
  {
    id: "track-13",
    title: "Candy Rain",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 290,
    cover: "/album-covers/miscellaneous_29.jpg",
    file: "/music/Candy Rain.mp3",
  },
  {
    id: "track-14",
    title: "Cavity",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 230,
    cover: "/album-covers/miscellaneous_30.jpg",
    file: "/music/Cavity.mp3",
  },
  {
    id: "track-15",
    title: "Cherish the Day",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 320,
    cover: "/album-covers/miscellaneous_31.jpg",
    file: "/music/Cherish the Day.mp3",
  }
]

