import type { Track } from "./types"

export const sampleTracks: Track[] = [
  
  {
    id: "track-00",
    title: "Just For Me",
    artist: "PinkPantheress ",
    album: "to - with it",
    duration: 134,
    cover: "/album-covers/Tomorrow - Image 195.jpg",
    file: "/music/Just For Me.mp3",
  },
  {
    id: "track-0",
    title: "Girls Just Want To Have Fun",
    artist: "Bladee",
    album: "Crest",
    duration: 134,
    cover: "/album-covers/miscellaneous_6.jpg",
    file: "/music/Girls Just Want To Have Fun.mp3",
  },

  {
    id: "track-1",
    title: "Talk talk",
    artist: "Charli XCX",
    album: "brat",
    duration: 272,
    cover: "/album-covers/miscellaneous_1.jpg",
    file: "/music/Talk talk.mp3",
  },
  {
    id: "track-2",
    title: "Sunshine",
    artist: "Steve Lacy",
    album: "Gemini Rights",
    duration: 272,
    cover: "/album-covers/miscellaneous_46.jpg",
    file: "/music/Sunshine.mp3",
  },
  {
    id: "track-3",
    title: "Coming Home",
    artist: "Beabadoobee",
    album: "This is How Tomorrow Moves",
    duration: 272,
    cover: "/album-covers/miscellaneous_15.jpg",
    file: "/music/Coming Home.mp3",
  },
  {
    id: "track-4",
    title: "Cool With You",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    duration: 272,
    cover: "/album-covers/miscellaneous_43.jpg",
    file: "/music/Cool With You.mp3",
  },
  {
    id: "track-8",
    title: "rose",
    artist: "jaydes",
    album: "rose",
    duration: 210,
    cover: "/album-covers/miscellaneous_22.jpg",
    file: "/music/rose.mp3",
  },
  {
    id: "track-9",
    title: "Seasons",
    artist: "Wave to Earth",
    album: "summer flows 0.02",
    duration: 300,
    cover: "/album-covers/miscellaneous_49.jpg",
    file: "/music/seasons.mp3",
  },
]
