import type { Track } from "./types"

export const sampleTracks: Track[] = [
  {
    id: "track-1",
    title: "365",
    artist: "Charli XCX",
    album: "365",
    duration: 217,
    cover: "/album-covers/miscellaneous_17.jpg",
    file: "/music/Best Friend.mp3",
  },
  {
    id: "track-2",
    title: "All I Need",
    artist: "Unknown Artist",
    album: "All I Need",
    duration: 240,
    cover: "/album-covers/miscellaneous_18.jpg",
    file: "/music/All I Need.mp3",
  },
  {
    id: "track-3",
    title: "Angel",
    artist: "From Barbie The Album",
    album: "Barbie The Album",
    duration: 180,
    cover: "/album-covers/miscellaneous_19.jpg",
    file: "/music/Angel (From Barbie The Album).mp3",
  },
  {
    id: "track-4",
    title: "Asleep Among Endives",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 300,
    cover: "/album-covers/miscellaneous_20.jpg",
    file: "/music/Asleep Among Endives.mp3",
  },
  {
    id: "track-5",
    title: "BLUE LAGOON",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 300,
    cover: "/album-covers/miscellaneous_21.jpg",
    file: "/music/BLUE LAGOON.mp3",
  },
  {
    id: "track-6",
    title: "BOY",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 240,
    cover: "/album-covers/miscellaneous_22.jpg",
    file: "/music/BOY.mp3",
  },
  {
    id: "track-7",
    title: "Been Ballin",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 180,
    cover: "/album-covers/miscellaneous_23.jpg",
    file: "/music/Been Ballin.mp3",
  },
  {
    id: "track-8",
    title: "Before I Let Go",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 300,
    cover: "/album-covers/miscellaneous_24.jpg",
    file: "/music/Before I Let Go.mp3",
  },
  {
    id: "track-9",
    title: "Best Friend",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 270,
    cover: "/album-covers/miscellaneous_25.jpg",
    file: "/music/Best Friend.mp3",
  },
  {
    id: "track-10",
    title: "Binibini",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 230,
    cover: "/album-covers/miscellaneous_26.jpg",
    file: "/music/Binibini.mp3",
  },
  {
    id: "track-11",
    title: "Black & Tan",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 180,
    cover: "/album-covers/miscellaneous_27.jpg",
    file: "/music/Black & Tan.mp3",
  },
  {
    id: "track-12",
    title: "Bubble Gum",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 210,
    cover: "/album-covers/miscellaneous_28.jpg",
    file: "/music/Bubble Gum.mp3",
  },
  {
    id: "track-13",
    title: "Candy Rain",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 290,
    cover: "/album-covers/miscellaneous_29.jpg",
    file: "/music/Candy Rain.mp3",
  },
  {
    id: "track-14",
    title: "Cavity",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 230,
    cover: "/album-covers/miscellaneous_30.jpg",
    file: "/music/Cavity.mp3",
  },
  {
    id: "track-15",
    title: "Cherish the Day",
    artist: "Unknown Artist",
    album: "Unknown Album",
    duration: 320,
    cover: "/album-covers/miscellaneous_31.jpg",
    file: "/music/Cherish the Day.mp3",
  }
]

